### ISSUE TITLE
LocalPed exception after resource restart (v1 compat)

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#206]
![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/e60ad263-0866-49d7-b1b0-f0f293928e45)

code to reproduce (v1 compat):
```js
import { LocalPed } from "alt-client";
import { Vector3, logError } from "alt-shared";

async function main() {
    const ped = new LocalPed('mp_f_freemode_01', 0, new Vector3(-0.7, 0, 71), Vector3.zero, false, 0)
}

main().catch(logError)
```

**Comment by Yiin** [comment]
does calling main in another tick fixes that?

**Comment by Yiin** [comment]
Okay so for some reason sometimes onBaseObjectCreate is called after onGameEntityCreate, resulting in entity not being registered before passing it to event handlers:

![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/e6277b0a-c3d0-432c-bb5c-b170152fae4f)

Will push a temp fix for it because it is breaking my scripts at current state.

**Comment by Yiin** [comment]
Can't reproduce this anymore, can you confirm? @xxshady

**Comment by xxshady** [comment]
still happens after reconnect

**Comment by xxshady** [comment]
fixed 

![image](https://github.com/user-attachments/assets/a7f64d80-8793-42a2-a6e8-b81c58f1baaa)
